sudo: false

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
 
cache: pip

install:
  - pip install -q -e .
  - pip install codecov
  
script:
  - python setup.py test
  - coverage run tests.py
  
after_success:
  - codecov
